name: CI - Monitor Economico Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/monitor-economico-frontend

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node (Angular)
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.0

      - name: Instalar dependências
        run: npm install

      - name: Build frontend
        run: npm run build


  e2e-cypress:
    runs-on: ubuntu-latest
    needs: build-frontend

    defaults:
      run:
        working-directory: frontend/monitor-economico-frontend

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node (Cypress)
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Instalar dependências
        run: npm install

      - name: Subir frontend
        run: npm run start &

      - name: Aguardar frontend
        run: npx wait-on http://localhost:4200

      - name: Rodar testes Cypress
        run: npx cypress run --spec "cypress/e2e/**/*.cy.ts"